export const SWITCH_TAB = 'SWITCH_TAB';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const ADD_FOLLOWING = 'ADD_FOLLOWING';
export const REMOVE_FOLLOWING = 'REMOVE_FOLLOWING';
export const SWITCH_EXT_NAMESPACE = 'SWITCH_EXT_NAMESPACE';
export const SWITCH_MY_NAMESPACE = 'SWITCH_MY_NAMESPACE';