export const SWITCH_TAB = 'SWITCH_TAB';
export const UPDATE_INPUT = 'UPDATE_INPUT';
//export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
//export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';
export const ADD_FOLLOWING = 'ADD_FOLLOWING';
export const REMOVE_FOLLOWING = 'REMOVE_FOLLOWING';